name: pointnetSeg
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - pytorch==2.5.1
  - matplotlib==3.9.2
  - numpy==2.1.3
  - open3d==0.18.0
  - pandas==2.2.3
  - pretrainedmodels==0.7.4
  - pytables==3.10.1
  - timm==1.0.11
  - torchaudio==2.5.1
  - torchmetrics==1.5.2
  - torchvision==0.20.1
  - scikit-learn==1.5.1
  - seaborn==0.13.2
